### ISSUE TITLE
Wrong origin specified for CORS policy

### ISSUE THREAD

**Issue by deisner** [mihailgaberov/pizza-app#2]
https://github.com/mihailgaberov/pizza-app/blob/0188a5c6b14026b9441f02634fd2b882e3f6b29b/backend/Startup.cs#L41

I may be mistaken, but I think this should be ` .WithOrigins("https://localhost:8080");`, since the request is coming from the frontend. Making this change fixed a CORS error message in the console that I was getting whenever I launched the frontend.

**Comment by deisner** [comment]
Never mind, I *am* mistaken. I didn't see that I'm supposed to be launching the frontend from https://localhost:5001/, not from https://localhost:8080/. It might be a good idea to put that in the README.

**Comment by mihailgaberov** [comment]
Glad you solved it. I am going to add it to the README. Thank you.
